### ISSUE TITLE
findAnime('pictures') promisestatus: reject // 404 error

### ISSUE THREAD

**Issue by FaMouZx3** [xy137/jikan-node#2]
Hello,

I'm not sure if I found a bug or if I just did something wrong, but I wanted to use the .findAnime function to display the pictures from MAL. Unfortunately I get a promisestatus after calling the function: reject with the error code 404.

AnimeID is correct --> MAL has images to the anime --> other functions work

Maybe an idea why that might be?

Thanks for the help in advance

![image](https://user-images.githubusercontent.com/22376982/54201375-c5430900-44cd-11e9-95ba-68bb1daa77bf.png)

**Comment by xy137** [comment]
hi! 

can you show me the line where you’re making the request?

**Comment by FaMouZx3** [comment]
Sorry, ofc i can :)

![image](https://user-images.githubusercontent.com/22376982/54259600-9f1d7780-4566-11e9-9fce-98b9ec03eb3e.png)

**Comment by xy137** [comment]
`var Pictures = Mal.findAnime(results[0].animeID, 'pictures')` should fix it.

You only need to specify a page if there are multiple pages and you want to get a certain page (which is what `1` is doing). If you specify a page when there is only 1 page, it will 404.

**Comment by FaMouZx3** [comment]
That's how it works perfectly. 

Thanks for the help :)
