### ISSUE TITLE
package.json license not matching the one used

### ISSUE THREAD

**Issue by lucas-deangelis** [xy137/jikan-node#3]
As said in the title,  in the repository the [LICENSE file](https://github.com/xy137/jikan-node/blob/master/LICENSE) is the GNU GPL, whereas in the package.json there is:
```
 "license": "ISC",
```
I'm by no means an expert on licenses, but I think it would be great to clarify which one applies to this project, since ISC and GNU GPL don't have the same rules.

One example of real issue would be [this project](https://github.com/njasi/AnimeDownloader), which uses yours but is licensed under ISC, which wouldn't be allowed by the GNU GPL if I'm not mistaken.

**Comment by xy137** [comment]
ive updated the license for jikan-node
